name: Release Vanaland Canary

on:
  push:
    branches:
      - master

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          yarn
      - name: Release Mac Version
        run: npm run release:mac
      - name: Create Release
        id: create_release
        uses: ./actions/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          replace_old_tag: true
          tag_name: canary-mac
          release_name: Mac Canary
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/vanaland.dmg
          asset_name: vanaland.dmg
          asset_content_type: application/zip

  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - name: install node tools
        run: npm install --global --production windows-build-tools@4.0.0
      - name: install node-gyp
        run: npm install --global node-gyp@latest
      - name: Set node config to use python2.7
        run: npm config set python python2.7
      - name: Set node config to set msvs_version to 2015
        run: npm config set msvs_version 2015
      - name: Install Dependencies
        run: npm install
      - name: Release Windows Version
        run: npm run release:win
      - name: Pack Windows dist
        run: npm run pack
      - name: Create Release
        id: create_release
        continue-on-error: true
        uses: ./actions/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          replace_old_tag: true
          tag_name: canary-win
          release_name: Windows Canary
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/vanaland.zip
          asset_name: vanaland.zip
          asset_content_type: application/zip
      - name: Upload Release Exe Asset
        id: upload-release-exe-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/vanaland.exe
          asset_name: vanaland.exe
          asset_content_type: application/exe
