name: Release Vanaland Canary Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_docker_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vanaland/vanaland
          tags: canary
